name: Manual Trigger Workflow

# Workflow trigger
on:
  workflow_dispatch:  # Enables the manual trigger

jobs:
  run-static-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 sagemaker

      - name: Run Python script
        run: |
          python code/deployment/sagemaker_training_job.py  # Replace 'your_script.py' with the path to your Python script
        env:
          AWS_PROFILE_NAME: ${{ secrets.AWS_PROFILE_NAME }}
          IMAGE_ECR_URI: ${{ secrets.IMAGE_ECR_URI }}
          SAGEMAKER_EXECUTION_ROLE: ${{ secrets.SAGEMAKER_EXECUTION_ROLE }}
          SAGEMAKER_TJ_INPUT_DATA_PATH: ${{ secrets.SAGEMAKER_TJ_INPUT_DATA_PATH }}
          SAGEMAKER_TJ_OUTPUT_PATH: ${{ secrets.SAGEMAKER_TJ_OUTPUT_PATH }}

