name: Run Script CI/CD

# Controls when the action will run
on:
  push:
    branches:
      - experiments  # Triggers the workflow on push to the main branch

# The jobs to be run
jobs:
  run-script:
    runs-on: ubuntu-latest  # Specify the OS to run the job

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace with your desired Python version

      # - name: Install dependencies
      #   run: pip install -r requirements.txt  # If you have a requirements.txt file

      - name: Run the script
        run: python tests/main2.py  # Replace with your script
